FROM debian
LABEL maintainer="khuziz@hotmail.com"

RUN apt-get update
RUN apt-get install -y curl gnupg apt-transport-https

RUN mkdir /data
WORKDIR /data

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'

RUN apt-get update
RUN apt-get install -y powershell

CMD pwsh