FROM debian
LABEL maintainer="khuziz@hotmail.com"

RUN apt-get update

RUN apt-get -qy install ucarp

ADD ucarp-run.sh /ucarp/run.sh
ADD ucarp-ucarp.sh /ucarp/ucarp.sh
ADD ucarp-down.sh /ucarp/down.sh
ADD ucarp-up.sh /ucarp/up.sh

RUN chmod +x /ucarp/run.sh
RUN chmod +x /ucarp/ucarp.sh

WORKDIR /ucarp
ENTRYPOINT ["/ucarp/run.sh"]
