version: '3.5'

networks:
  frontend:
  backend:
  shared-backend:
    name: shared-backend

services:

  nodeexporter:
    image: quay.io/prometheus/node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host

  alertmanager:
    image: quay.io/prometheus/alertmanager
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
    # ports:
    #   - 9093:9093

  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    networks:
      - backend
    # ports:
    #   - 9091:9091

  prometheus:
    image: quay.io/prometheus/prometheus
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - nodeexporter
      - alertmanager
      - pushgateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/prometheus/alertrules.yml
    # ports:
    #   - 91:9090

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - backend
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    depends_on:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    # ports:
    #   - 90:3000

  netcoreconsole:
    build:
      context: NetCoreConsole/
    image: netcoreconsole
    restart: unless-stopped
    networks:
      - backend

  bauth:
    build:
      context: ../BAuth/
    image: bauth
    restart: unless-stopped
    networks:
      - shared-backend
    # ports:
    #   - "81:80"

  nginx:
    image: nginx
    restart: unless-stopped
    networks:
      - frontend
      - backend
      - shared-backend
    depends_on:
      - bauth
      - pushgateway
      - prometheus
      - grafana
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"   # grafana /w bauth
      - "81:81"   # grafana
      - "90:90"   # prometheus
      - "91:91"   # pushgateway
      - "93:93"   # alertmanager