version: '3'
services:
  nodeexporter:
    image: quay.io/prometheus/node-exporter
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  alertmanager:
    image: quay.io/prometheus/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.role == worker]
        # due to volume; we cant deploy on worker unless we make the required files availables on all
        # workers (and we might need to provide absolute path)
        constraints: [node.role == manager]
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
  prometheus:
    image: quay.io/prometheus/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.role == worker]
        constraints: [node.role == manager]
    volumes:
      - ./prometheus.v3.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/prometheus/alertrules.yml
  grafana:
    image: grafana/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.role == worker]
        constraints: [node.role == manager]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
  netcoreconsole:
    image: 192.168.10.14:5000/netcoreconsole
    # we cant build this image in v3 compose / stack deploy; build it yourself first and push to some registry
    # http://weblogs.com.pk/khurram/archive/2017/03/21/docker-registry.aspx
    deploy:
      mode: global
  bauth:
    image: 192.168.10.14:5000/bauth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
  nginx:
    image: nginx
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "./nginx.v3.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"