version: '3.3'
configs:
  # https://docs.docker.com/engine/swarm/configs
  alertmanagerconfig:
    file: ./alertmanager-config.yml
  prometheusconfig:
    file: ./prometheus.v3.yml
  alertrulesconfig:
    file: ./alertrules.yml
  grafanadatasourceconfig:
    file: ./grafana-datasource.yml
  grafanadashboardconfig:
    file: ./dashboards/dashboard.yml
  grafanajsonfirst:
    file: ./dashboards/first.json
  nginxconfig:
    file: ./nginx.conf
services:
  nodeexporter:
    image: quay.io/prometheus/node-exporter
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  alertmanager:
    image: quay.io/prometheus/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    configs:
      - source: alertmanagerconfig
        target: /etc/alertmanager/config.yml
        # https://docs.docker.com/compose/compose-file/#long-syntax
  prometheus:
    image: quay.io/prometheus/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    extra_hosts:
      - "swarm1:192.168.10.14"
      - "swarm2:192.168.10.15"
      - "swarm3:192.168.10.16"
    configs:
      - source: prometheusconfig
        target: /etc/prometheus/prometheus.yml
      - source: alertrulesconfig
        target: /etc/prometheus/alertrules.yml
  grafana:
    image: grafana/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    configs:
      - source: grafanadatasourceconfig
        target: /etc/grafana/provisioning/datasources/datasource.yml
      - source: grafanadashboardconfig
        target: /etc/grafana/provisioning/dashboards/dashboard.yml
      - source: grafanajsonfirst
        target: /etc/grafana/provisioning/dashboards/first.json
  netcoreconsole:
    image: 192.168.10.14:5000/netcoreconsole
    # we cant build this image in v3 compose / stack deploy; build it yourself first and push to some registry
    # http://weblogs.com.pk/khurram/archive/2017/03/21/docker-registry.aspx
    deploy:
      mode: global
  bauth:
    image: 192.168.10.14:5000/bauth
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
  nginx:
    image: nginx
    deploy:
      placement:
        constraints: [node.role == manager]
    configs:
      - source: nginxconfig
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"   # grafana /w bauth
      - "81:81"   # grafana
      - "90:90"   # prometheus
      - "91:91"   # pushgateway
      - "93:93"   # alertmanager