version: '3.5' # 3.5 for network/middletier external / static name

networks:
  fronttier:
  middletier:
    name: middletier
  backtier:

services:

  nodeexporter:
    image: quay.io/prometheus/node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host

  # middletier (nginx)
  alertmanager:
    image: quay.io/prometheus/alertmanager
    restart: unless-stopped
    networks:
      - middletier
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
    # ports:
    #   - 9093:9093

  # middletier (nginx)
  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    networks:
      - middletier
    # ports:
    #   - 9091:9091

  # backtier, middletier (nginx)
  prometheus:
    image: quay.io/prometheus/prometheus
    restart: unless-stopped
    networks:
      - backtier
      - middletier
    depends_on:
      - nodeexporter
      - alertmanager
      - pushgateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/prometheus/alertrules.yml
    # ports:
    #   - 91:9090

  # middletier (nginx)
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - middletier
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    depends_on:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    # ports:
    #   - 90:3000

  # backtier
  netcoreconsole:
    build:
      context: NetCoreConsole/
    image: khurramaziz/prometheusapp
    restart: unless-stopped
    networks:
      - backtier

  # middletier (nginx)
  bauth:
    build:
      context: ../BAuth/
    image: khurramaziz/bauth
    restart: unless-stopped
    networks:
      - middletier
    # ports:
    #   - "81:80"

  # fronttier (ports), middletier
  nginx:
    image: nginx
    restart: unless-stopped
    networks:
      - fronttier
      - middletier
    depends_on:
      - bauth
      - pushgateway
      - prometheus
      - grafana
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"   # grafana /w bauth
      - "81:81"   # grafana
      - "90:90"   # prometheus
      - "91:91"   # pushgateway
      - "93:93"   # alertmanager