version: '2'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host
  alertmanager:
    image: quay.io/prometheus/alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
  prometheus:
    image: quay.io/prometheus/prometheus
    restart: unless-stopped
    links:
      - node-exporter
      - alertmanager
    depends_on:
      - node-exporter
      - alertmanager
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/prometheus/alertrules.yml
    # ports:
    #   - 91:9090
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    links:
      - prometheus
    depends_on:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    # ports:
    #   - 90:3000
  bauth:
    build:
      context: BAuth/
    image: khurram-aziz/bauth
    restart: unless-stopped
    # ports:
    #   - "71:80"
  nginx:
    image: nginx
    restart: unless-stopped
    links:
      - grafana
      - bauth
    depends_on:
      - bauth
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"