version: '3'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # v3 compose / stack deploy doesnt support host networking / host pid
    # Mounting required paths for node-exporter
    # https://github.com/vegasbrianc/prometheus/blob/master/docker-stack.yml
  alertmanager:
    image: quay.io/prometheus/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints: [node.role == manager]
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
  prometheus:
    image: quay.io/prometheus/prometheus
    deploy:
      placement:
        constraints: [node.role == manager]
    extra_hosts:
      - "swarm1:192.168.10.14"
      - "swarm2:192.168.10.15"
      - "swarm3:192.168.10.16"
    depends_on:
      - node-exporter
      - alertmanager
    volumes:
      - ./prometheus.v3.yml:/etc/prometheus/prometheus.yml
      - ./alertrules.yml:/etc/prometheus/alertrules.yml
    ports:
      - 91:9090
  grafana:
    image: grafana/grafana
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    depends_on:
      - prometheus
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 90:3000
  netcoreconsole:
    image: 192.168.10.14:5000/netcoreconsole
    # we cant build this image in v3 compose / stack deploy; build it yourself first and push to some registry
    # http://weblogs.com.pk/khurram/archive/2017/03/21/docker-registry.aspx
    deploy:
      mode: global
  bauth:
    image: 192.168.10.14:5000/bauth
    # we cant build this image in v3 compose / stack deploy; build it yourself first and push to some registry
    # http://weblogs.com.pk/khurram/archive/2017/03/21/docker-registry.aspx
    deploy:
      # placement:
      #   constraints: [node.role == manager]
      mode: replicated
      replicas: 1
  nginx:
    image: nginx
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - bauth
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"