apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  version: 1
  editable: true
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false