global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - 'alertrules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  dns_sd_configs:
    - names:
      - 'tasks.nodeexporter'
      type: 'A'
      port: 9100
      # https://docs.docker.com/docker-cloud/apps/service-links
- job_name: pushgateway
  metrics_path: /metrics
  static_configs:
  - targets:
    - pushgateway:9091
- job_name: docker-metrics # https://docs.docker.com/config/thirdparty/prometheus
  static_configs:
  - targets:
      - 'swarm1:9323'
      - 'swarm2:9323'
      - 'swarm3:9323'
- job_name: netcoreconsole
  metrics_path: /metrics
  dns_sd_configs:
    - names:
      - 'tasks.netcoreconsole'
      type: 'A'
      port: 8000