global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - 'alertrules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  static_configs:
  - targets:
    # docker-for-windows-vm address
    - 10.0.75.2:9100
    # - linux-server2-running-node-exporter:9100
#- job_name: wmi
#  static_configs:
#  - targets:
#    - windows-server1-running-wmi-exporter:9182
#    - windows-server2-running-wmi-exporter:9182
- job_name: pushgateway
  metrics_path: /metrics
  static_configs:
  - targets:
    - pushgateway:9091
- job_name: docker-metrics # https://docs.docker.com/config/thirdparty/prometheus
  static_configs:
  # docker-for-windows-vm address
  - targets: ['10.0.75.1:9323']
- job_name: netcoreconsole
  metrics_path: /metrics
  static_configs:
  - targets:
    - 10.0.75.1:8000 # net4console on host
    - netcoreconsole:8000