version: '3'
services:
    zoo1:
        image: zookeeper
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        deploy:
            placement:
                constraints:
                - node.hostname == swarm1
    zoo2:
        image: zookeeper
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        deploy:
            placement:
                constraints:
                - node.hostname == swarm2
    zoo3:
        image: zookeeper
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        deploy:
            placement:
                constraints:
                - node.hostname == swarm3
