version: '3.5'

networks:
  frontend:
  backend:
  shared-backend:
    name: shared-backend

volumes:
  elasticsearch: {}

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # ports:
    #   - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash-hello.conf:/usr/share/logstash/pipeline/logstash-hello.conf
      - ./logstash-syslog.conf:/usr/share/logstash/pipeline/logstash-syslog.conf
    ports:
      - "5000:5000"
      - "5000:5000/udp"
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - elasticsearch
    # ports:
    #   - "5601:5601"

  bauth:
    build:
      context: ../BAuth/
    image: bauth
    restart: unless-stopped
    networks:
      - shared-backend
    # ports:
    #   - "80:80"

  nginx:
    image: nginx
    restart: unless-stopped
    networks:
      - frontend
      - backend
      - shared-backend
    depends_on:
      - bauth
      - elasticsearch
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"   # kibana /w bauth
      - "81:81"   # kibana
      - "90:90"   # elasticsearch