version: '2'

# volumes:
#   elasticsearch: {}

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    restart: unless-stopped
    volumes:
      # - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # we dont need to expose it unless we want to access it directly
    # ports:
    #   - "90:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash-hello.conf:/usr/share/logstash/pipeline/logstash-hello.conf
    ports:
    - 5000:5000/udp
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "80:5601"