version: '2'
services:
    redis:
        image: redis
        restart: unless-stopped
    mvc:
        build:
            context: .
            dockerfile: Dockerfile
        image: khurramaziz/mvcapp2
        restart: unless-stopped
        ports:
            - 5000:80
        links:
            - redis
        depends_on: 
            - redis