version: '2.0'

services:

  zookeeper:
    image: zookeeper
    restart: unless-stopped
  
  kafka:
    build:
      context: KafkaServer/
    image: khurramaziz/kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    # https://kafka.apache.org/quickstart
    volumes:
      - ./kafka-server.properties:/config/server.properties
    entrypoint:
      - /kafka/bin/kafka-server-start.sh
      - /config/server.properties
  
  kafkaapp:
    # https://www.codeguru.com/csharp/.net/producer-and-consumer-for-kafka-in-.net-an-exploration.html
    # https://www.infoworld.com/article/3215165/application-development/how-to-use-apache-kafka-messaging-in-net.html
    # https://www.hugopicado.com/2017/11/22/getting-started-with-net-core-and-kafka.html
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    restart: unless-stopped
    # command: producer
    depends_on:
      - kafka