version: '2.0'

volumes:
  zookeeper: {}
  zookeeperlog: {}
  kafka: {}

services:

  zookeeper:
    image: zookeeper
    restart: unless-stopped
    volumes:
      - zookeeper:/data
      - zookeeperlog:/datalog
  
  kafka:
    build:
      context: KafkaServer/
    image: khurramaziz/kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    # https://kafka.apache.org/quickstart
    volumes:
      - ./kafka-server.properties:/config/server.properties
      - kafka:/data
    entrypoint:
      - /kafka/bin/kafka-server-start.sh
      - /config/server.properties
  
  setup:
    build:
      context: KafkaServer/
    image: khurramaziz/kafka
    depends_on:
      - kafka
    volumes:
      - ./wait.sh:/wait.sh
    entrypoint:
      - ./wait.sh
    command: /kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 4 --topic testtopic

  # zookeeperwebui:
  #   image: tobilg/zookeeper-webui
  #   restart: unless-stopped
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     - ZK_DEFAULT_NODE=zookeeper:2181
  #   ports:
  #     - 90:8080
  
  # kafkawebui:
  #   image: hwestphal/kafka-web-console
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 91:9000
  
  # test:
  #   build:
  #     context: KafkaServer/
  #   image: khurramaziz/kafka
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./wait.sh:/wait.sh
  #   entrypoint:
  #     - ./wait.sh
  #   command: /kafka/bin/kafka-topics.sh --list --zookeeper zookeeper:2181

  p1:
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    # restart: unless-stopped
    # producer|consumer topic partition how-many-messages
    command: producer testtopic 0 3
    depends_on:
      - kafka
      - setup
  p2:
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    # restart: unless-stopped
    command: producer testtopic 1,2 3
    depends_on:
      - kafka
      - setup
  p3:
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    # restart: unless-stopped
    command: producer testtopic 3 3
    depends_on:
      - kafka
      - setup

  c1:
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    restart: unless-stopped
    command: consumer testtopic 0
    depends_on:
      - kafka
      - setup
  c2:
    build:
      context: KafkaNetCoreConsole/
    image: khurramaziz/kafkaapp
    restart: unless-stopped
    command: consumer testtopic 1,2,3
    depends_on:
      - kafka
      - setup