version: '2'
services:
    redis:
        image: redis
        restart: unless-stopped
    mvc:
        build:
            context: RedisMvc
            dockerfile: Dockerfile
        image: khurramaziz/mvcapp
        restart: unless-stopped
        ports:
            - 8000:80
        links:
            - redis
        depends_on: 
            - redis